#!/usr/bin/env python3
import pandas as pd
import numpy as np
from matplotlib import cm as cm
from matplotlib import pyplot as plt
import seaborn as sns
import matplotlib

'''
This script takes the Orthogroups.GeneCount.tsv file generated by OrthoFinder and plots
the number of shared orthogroups for all pairwise combinations of strains.
This version (norm2) compensates for the variation in total number of genes by normalising
each count by the geometric mean of the total gene counts in the two strains.
'''


figure_file = "shared_genes_norm3_v_ANIb.pdf"


#read in the ANI table
dfANI = pd.read_csv('/Users/peter/Documents/Manuscripts/R_leg_genospecies/data/leg-anh_2020-09-18/ANI/445_ANI.tab', names = ['Query_name', 'Reference_name', 'ANI', 'Fragments', 'Matches'], sep="\t")

dfANI['Query_name'] = dfANI['Query_name'].str.strip('.fna')
dfANI['Reference_name'] = dfANI['Reference_name'].str.strip('.fna')

#read in the shared genes table
df2 = pd.read_csv('/Users/peter/Documents/Manuscripts/R_leg_genospecies/data/leg-anh_2020-09-18/Orthofinder/all_runs/df_all_concat4.csv')


#merge the orthogroup and ANI dataframes
df_merged = pd.merge(df2, dfANI, how='left', left_on=['Str1', 'Str2'], right_on = ['Query_name','Reference_name'])

df_merged = df_merged.rename(columns = {'Shared_norm':'Gene sharing index'}) 


sns.set(font_scale=2)
sns.set_style("white")
sns.set_style("ticks")

ax = plt.figure(figsize=(10, 10))

ax = sns.scatterplot(
    data = df_merged,
    x='ANI', 
    y='Gene sharing index', 
    marker='.', 
    alpha = 0.3) 

plt.savefig(figure_file)
